name: action workflows
on : [push ]
jobs:
  runs-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple javascript action
        id : hello
        uses: actions/hello-world-javascript-action@v1

        with:
          who-to-greet: devopshint

      - name : get the output time 
        run : echo "${{steps.hello.output.time }}" 



 